### ISSUE TITLE
Abrir Nueva vista

### ISSUE THREAD

**Issue by danylop0423** [danylop0423/learning_android#4]
Crear un botón que abra una nueva vista

**Comment by JaviAlejos** [comment]
En la actividad principal "MainActivity" aparece un botón "My Map". Cuando se le da, abre un google map (coordinadas por defecto) en otra actividad.

**Comment by JaviAlejos** [comment]
Para que funcione el mapa hay que configurar unas cosillas... Creo que al hacer el pull, os debería funcionar pero si no se os ve el mapa me decís jejeje
